$p = @"
{"type":"block_actions","team":{"id":"TJXFZUU3D","domain":"pslickposh"},"user":{"id":"UK8ULCFK2","username":"m.george.brown89","name":"m.george.brown89","team_id":"TJXFZUU3D"},"api_app_id":"AJXGBKHCK","token":"bvwrkiHtNJNy5dBc65Kq9zyY","container":{"type":"message","message_ts":"1570898209.007000","channel_id":"CJXGA1QSW","is_ephemeral":false},"trigger_id":"787021064145.643543980115.d05ceefb00e453cdb9de78f92d61e584","channel":{"id":"CJXGA1QSW","name":"pslickpslack-testing"},"message":{"type":"message","subtype":"bot_message","text":"This content can't be displayed.","ts":"1570898209.007000","username":"PSlickPoSH","bot_id":"BJXGCSG67","blocks":[{"type":"section","block_id":"titleSection","text":{"type":"mrkdwn","text":"*Slack PowerShell Module User Testing!*","verbatim":false}},{"type":"divider","block_id":"divider1"},{"type":"section","block_id":"subTitleSection","text":{"type":"plain_text","text":"Testing stuff :smile:","emoji":true},"accessory":{"fallback":"1080x1080px image","image_url":"https:\/\/api.slack.com\/img\/blocks\/bkb_template_images\/beagle.png","image_width":1080,"image_height":1080,"image_bytes":1432686,"type":"image","alt_text":"a beagle"}},{"type":"divider","block_id":"divider2"},{"type":"section","block_id":"Section3","text":{"type":"plain_text","text":"We're still testing all the things. :+:","emoji":true},"fields":[{"type":"plain_text","text":"Title\nContent","emoji":true},{"type":"plain_text","text":"Title\nContent","emoji":true},{"type":"plain_text","text":"Title\nContent","emoji":true},{"type":"plain_text","text":"Title\nContent","emoji":true}]},{"type":"actions","block_id":"blockid123","elements":[{"type":"button","action_id":"ok","text":{"type":"plain_text","text":"OK","emoji":true}},{"type":"button","action_id":"ok2","text":{"type":"plain_text","text":"OK","emoji":true}},{"type":"button","action_id":"ok3","text":{"type":"plain_text","text":"OK","emoji":true}}]},{"type":"context","block_id":"7j6","elements":[{"type":"mrkdwn","text":"*Slack PowerShell Module User Testing!*","verbatim":false},{"type":"plain_text","text":"We're still testing all the things. :+:","emoji":true},{"fallback":"1080x1080px image","image_url":"https:\/\/api.slack.com\/img\/blocks\/bkb_template_images\/beagle.png","image_width":1080,"image_height":1080,"image_bytes":1432686,"type":"image","alt_text":"a beagle"}]}]},"response_url":"https:\/\/hooks.slack.com\/actions\/TJXFZUU3D\/793455493616\/LH4qlPpzEYKKpC7o5oCN21uI","actions":[{"action_id":"ok","block_id":"blockid123","text":{"type":"plain_text","text":"OK","emoji":true},"type":"button","action_ts":"1570914548.174600"}]}
"@
$Body = @{
    payload = $p
}

#Invoke-RestMethod -Uri "http://localhost:1000/api/slack" -Method Post -Body $Body

$LogsPath = (Split-Path -Parent (($PSScriptRoot)))| Join-Path -ChildPath "Logs"
$LogsPath
Out-File -FilePath "$LogsPath\test.json" -InputObject $P